[package]
name = "css"
version = "0.1.0"
edition = "2024"

[dependencies]
html.workspace = true
js.workspace = true

cssparser.workspace = true

log.workspace = true
anyhow.workspace = true
url.workspace = true