[package]
name = "rewrite_layout_flex"
version.workspace = true
edition.workspace = true

[dependencies]
rewrite_core = { path = "../../../core" }
rewrite_layout_size_impl = { path = "../size/impls" }

[lints]
workspace = true
