[workspace]
resolver = "3"
members = [
    "crates/*"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# Task handling
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1.17"

# Parsing
html5ever = "0.35.0"
cssparser = "0.35.0"

# Rendering
wgpu = "26.0.1"
winit = "0.30.12"

# Webpage handling
url = "2.5.7"
reqwest = { version = "0.12.23", features = ["stream"] }

# Data types
bytes = "1.10.1"
lasso = "0.7.3"
indextree = "4.7.4"
smallvec = "2.0.0-alpha.11"

# Logging and error handling
log = "0.4.28"
env_logger = "0.11.8"
anyhow = { version = "1.0.99", features = ["backtrace"] }

# Testing
headless_chrome = "1.0.18"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
urlencoding = "2.1.3"
once_cell = "1.19.0"

# Our crates
css = { path = "crates/css" }
html = { path = "crates/html" }
layouter = { path = "crates/layouter" }
page_handler = { path = "crates/page_handler" }
wgpu_renderer = { path = "crates/wgpu_renderer" }


[profile.dev]
opt-level = 1
lto = false

[profile.dev.package."*"]
opt-level = 3