[workspace]
resolver = "3"
members = [
    "crates/*"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# Task handling
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1.17"
rayon = "1.11.0"

# Parsing
html5ever = "0.35.0"
cssparser = "0.35.0"

# Rendering
wgpu = "26.0.1"
winit = "0.30.12"
bytemuck = { version = "1.18.0", features = ["derive"] }
glyphon ={ git = "https://github.com/grovesNL/glyphon", rev = "724ab57edbd6c59ba219cd99cf89925d056392db" }

# Webpage handling
url = "2.5.7"
reqwest = { version = "0.12.23", features = ["stream"] }

# Data types
bytes = "1.10.1"
lasso = "0.7.3"
indextree = "4.7.4"
smallvec = "2.0.0-alpha.11"
once_cell = "1.21.3"

# String stuff
unicode-linebreak = "0.1.5"
unicode-bidi = "0.3.18"

# Logging and error handling
log = "0.4.28"
env_logger = "0.11.8"
anyhow = { version = "1.0.99", features = ["backtrace"] }
tracing = "0.1.41"

# Testing
headless_chrome = "1.0.18"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
urlencoding = "2.1.3"
criterion = "0.7.0"

# JavaScript engine
rusty_v8 = "0.32.1"

# Our crates
css = { path = "crates/css" }
html = { path = "crates/html" }
layouter = { path = "crates/layouter" }
page_handler = { path = "crates/page_handler" }
wgpu_renderer = { path = "crates/wgpu_renderer" }
style_engine = { path = "crates/style_engine" }
js_engine_v8 = { path = "crates/js_engine_v8" }
js = { path = "crates/js" }


[profile.dev]
opt-level = 1
lto = false

[profile.dev.package."*"]
opt-level = 3