check-private-items = true

allowed-idents-below-min-chars = ["V8", "id", "x", "y", "f", "x0", "y0", "x1", "y1", "_", "'_"]
absolute-paths-max-segments = 0
cognitive-complexity-threshold = 15
enforce-iter-loop-reborrow = true
excessive-nesting-threshold = 5
min-ident-chars-threshold = 2
# ConstraintSpace has 5 bools to match Chromium LayoutNG model
max-struct-bools = 5
too-many-arguments-threshold = 5
too-many-lines-threshold = 75
type-complexity-threshold = 125
