check-private-items = true

allowed-idents-below-min-chars = ["V8"]
absolute-paths-max-segments = 0
cognitive-complexity-threshold = 15
enforce-iter-loop-reborrow = true
excessive-nesting-threshold = 5
min-ident-chars-threshold = 2
too-many-arguments-threshold = 5
too-many-lines-threshold = 75
type-complexity-threshold = 125