[package]
name = "style_engine"
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1"
js = { path = "../../../js" }
css = { path = "../../" }
css_core = { path = "../core" }
