[package]
name = "style_engine"
edition.workspace = true

[dependencies]
anyhow.workspace = true
html.workspace = true
css.workspace = true
log.workspace = true
csscolorparser = "0.6"

[dev-dependencies]
env_logger.workspace = true
